### ISSUE TITLE
Question - qbittorrent-nox static

### ISSUE THREAD

**Issue by misterkoko** [notsure2/dpiprobe#5]
Hello!

Sorry, I didn't know how else to reach you.

Do you happen to have an updated bash script for building qbittorrent?

I used your script - https://gist.github.com/notsure2/e3c3ec6897f801d00cf491fedb70bf4d but I am wondering if you have it updated / or could update it for the latest releases:

QT v5.15.2
Libtorrent v1.2.14
Qbittorrent-nox release-4.3.6

I get stuck right at the end on building qbittorrent - it says it can't find libtorrent.a but I build headers on boost (./b2 headers)

The ubuntu one is probably easier to update than your Debian 9 (https://gist.github.com/notsure2/f8eac873eb7298d89d551047779d8361) one correct?

Cheers!

**Comment by notsure2** [comment]
Look into which is based on my gists originally: https://github.com/userdocs/qbittorrent-nox-static
